client:
  endpoint:
    user: http://127.0.0.1:${server.port}
opentracing:
  jaeger:
    enabled: true
    udp-sender:
      host: localhost
      port: 6831
spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        username: admin
        password: admin
        url: http://localhost:8080
  datasource:
    primary:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring-boot-archetype?useUnicode=true&characterEncoding=utf8&useSSL=false
    biz:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring-boot-biz?useUnicode=true&characterEncoding=utf8&useSSL=false
jwt:
  enable: true
  key:
    public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVzGnxfi1/yynVn0O+fjdyfy+E0o1PFDxWF0RUz6Xv+vtRrShzcG5ovioL+XYtybGv1tR0e80sQKcbytmfpU/DndQSiH1oDmrmcAVC3ohS0Tpt4m7lTPnbzpLwg/3Mo6VlczaB2MEgtO3MQCr0qVX0YSjX1dJAVUWBchV2CLCyMQIDAQAB
    private: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJXMafF+LX/LKdWfQ75+N3J/L4TSjU8UPFYXRFTPpe/6+1GtKHNwbmi+Kgv5di3Jsa/W1HR7zSxApxvK2Z+lT8Od1BKIfWgOauZwBULeiFLROm3ibuVM+dvOkvCD/cyjpWVzNoHYwSC07cxAKvSpVfRhKNfV0kBVRYFyFXYIsLIxAgMBAAECgYB4HAMGgylwQjI0+xKSdxl2UMyFL13mfk8yqE09w5FFrnQ8tR6uEQQ2L+P+3fMIG6TBXPvUuj90sBJNkoSUITSmYu2BReSH5/POyHMcFdod5INFTYITHPHlygON6xedpIwFQ700CYS6PAgizsierlzTXVoe2B3XHvrtGRWdj4hekQJBAORv/+TzpsyJtg4TSxu2zgfoJAHDqQ7scqooGgN2PEyz3tXM0fNGUYe9ZZnk1tvWeav60yy3trx0A9bIYazzn38CQQCn32ea1pBNxKCWUR618kIM4IPT92ghu6FS1CVLXJdunKu9GyfiPb0HzTLWx5mbthLF82aIV7/sLGqWW5Ce+oZPAkAxMxoXEo8TMHnAcFFV57paI5pVsvFfYHeVxEtOAZIdJwRQYeu6DKQUqysNySapdHkCHGSNFghKcGY/RSscV+A7AkBl9n25QGW5tppLcs4SeSjBJYUss/MduhdMdeqJEZ4w4xw06k+ZTSKJoIsmhWm5eCeC8EnwukuqKXg8BzWaOlRlAkEAsJTZ/FyLmjkq/lOnX+8VtQ5e52TH6qY0sUACkrCchbta/gwQPeE4mXEAMlrgyvhdYUZhSvnHET+tpV24ZnTwAw==
