name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: check
      run: ./gradlew checkcode
    - name: Check Docker version
      run: docker version
    - name: test
      run: ./gradlew test aggregateJacocoReport
    - uses: codecov/codecov-action@v1
#      if: endsWith(github.ref,'master') || endsWith(github.base_ref,'master')
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        files: build/reports/jacoco/aggregate/jacocoTestReport.xml
#        yml: ./codecov.yml #optional
        flags: unittests #optional
        name: codecov-jacoco #optional
