name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: |
        echo ${{ github.ref }} && ${{ github.base_ref }}
        mvn -B package --file pom.xml
    - name: Build Jacoco Report
      run: mvn jacoco:report-aggregate
      if: endsWith(github.ref,'master') || endsWith(github.base_ref,'master')
    - uses: codecov/codecov-action@v1
      if: endsWith(github.ref,'master') || endsWith(github.base_ref,'master')
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./archetype-report/target/site/jacoco-aggregate/jacoco.xml #optional
        flags: unittests #optional
        name: codecov-jacoco #optional
